// cs
export const increase = 'increase';
export const cutback = 'cutback';

// Toolbar
export const TOOLBAR_TURN_ON = 'TOOLBAR_TURN_ON';
export const TOOLBAR_IS_MN_OPEN = 'TOOLBAR_IS_MN_OPEN';
export const TOOLBAR_IS_MN_OFF = 'TOOLBAR_IS_MN_OFF';

// IllustrationBox
export const ILLUSTRATION_BOX_SET_CLIENT_WIDTH = 'ILLUSTRATION_BOX_SET_CLIENT_WIDTH';
export const ILLUSTRATION_BOX_SET_IMG_SIZE = 'ILLUSTRATION_BOX_SET_IMG_SIZE';

// IllustrationTop
export const ILLUSTRATION_TOP_SET_TOP_X = 'ILLUSTRATION_TOP_SET_TOP_X';
export const ILLUSTRATION_TOP_SET_INIT_X = 'ILLUSTRATION_TOP_SET_INIT_X';
export const ILLUSTRATION_TOP_SET_THIS_X = 'ILLUSTRATION_TOP_SET_THIS_X';
export const ILLUSTRATION_TOP_SET_DATE = 'ILLUSTRATION_TOP_SET_DATE';
export const ILLUSTRATION_TOP_SET_IMG_SIZE = 'ILLUSTRATION_TOP_SET_IMG_SIZE';
